### ISSUE TITLE
When uploading an svg file to the panel

### ISSUE THREAD

**Issue by flokuek** [sylvainjule/kirby-colorextractor#5]
When uploading a svg file to the panel it throws an error: `imagecreatefromstring(): Data is not in a recognized format`

same with a png file: `file_get_contents(http://localhost/peak/media/site/-772678704-1544528814/capture-1x0-q90.png): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found`

These issues come up since I've updated to the latest v3 nightly build 2018-12-10

blueprint setup:

```
sections:
  images:
    type: files
    layout: list
    template: image
    info: "{{ file.dimensions }}"
```

![error](https://i.imgur.com/HlIxuK0.png)
![error](https://i.imgur.com/96E4rgk.png)

**Comment by sylvainjule** [comment]
The svg issue is fixed, the plugin will now only process resizable files. ✅ 

Your png issue should also be fixed, the extraction process now relies on the `root()` instead of `url()` of the thumb, and forces its creations so it always exists when the path is accessed. Don't hesitate to open a new issue with more details about the context if it happens again!

**Comment by flokuek** [comment]
Awesome :)
